/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package userInterface;

import UI.*;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shivanirahatwad
 */
public class AppointmentBookingJFrame extends javax.swing.JFrame {

    /**
     * Creates new form AppointmentBookingJPanel
     */
    
      DefaultTableModel tblModel;
    private DefaultTableModel tblmodel;
    public AppointmentBookingJFrame() {
        initComponents();
        
          getContentPane().setBackground(Color.pink);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnlogout1 = new javax.swing.JButton();
        btnhome6 = new javax.swing.JButton();
        btnBook = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtHospital = new javax.swing.JTextField();
        txtPid = new javax.swing.JTextField();
        txtPatientname = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        txtDocName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtdt = new javax.swing.JTextField();
        txttime = new javax.swing.JTextField();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setText("BOOK APPOINTMENT");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 328, -1));

        btnlogout1.setBackground(new java.awt.Color(255, 255, 153));
        btnlogout1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnlogout1.setText("LOGOUT");
        btnlogout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogout1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnlogout1, new org.netbeans.lib.awtextra.AbsoluteConstraints(546, 21, -1, -1));

        btnhome6.setBackground(new java.awt.Color(204, 204, 204));
        btnhome6.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnhome6.setText("HOME");
        btnhome6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhome6ActionPerformed(evt);
            }
        });
        getContentPane().add(btnhome6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 90, 20));

        btnBook.setBackground(new java.awt.Color(0, 204, 102));
        btnBook.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnBook.setText("BOOK");
        btnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookActionPerformed(evt);
            }
        });
        getContentPane().add(btnBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 410, 100, 30));

        jLabel2.setText("Hospital Name:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 66, -1, -1));

        jLabel3.setText("Patient ID:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 101, -1, -1));

        jLabel4.setText("Patient Name:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 141, -1, -1));

        jLabel5.setText("Age:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 176, -1, -1));

        jLabel6.setText("Gender:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 210, -1, -1));

        jLabel7.setText("Phone Number:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 244, -1, -1));

        jLabel8.setText("Doctor Name:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 285, -1, -1));

        jLabel9.setText("Appointment Date:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 323, -1, -1));

        txtHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHospitalActionPerformed(evt);
            }
        });
        getContentPane().add(txtHospital, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 63, 138, -1));
        getContentPane().add(txtPid, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 98, 138, -1));
        getContentPane().add(txtPatientname, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 138, 138, -1));

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 173, 138, -1));

        jLabel10.setText("TIME:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 367, -1, -1));

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 241, 136, -1));

        jRadioButton1.setText("Female");
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 208, -1, -1));

        jRadioButton2.setText("Male");
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 208, -1, -1));

        jRadioButton3.setText("Other");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(515, 208, -1, -1));
        getContentPane().add(txtDocName, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 282, 136, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "HOSPITAL NAME", "PATIENT ID", "PATIENT NAME", "DOCTOR NAME", "APPOINTMENT DATE", "TIME"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 463, 695, 289));

        txtdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdtActionPerformed(evt);
            }
        });
        getContentPane().add(txtdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 320, 101, -1));
        getContentPane().add(txttime, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 364, 103, -1));

        btnCancel.setText("CANCEL APPOINTMENT");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 410, 200, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void btnhome6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhome6ActionPerformed
        // TODO add your handling code here:
         MainJFrame MainFram = new MainJFrame();
         MainFram.show();
         dispose();
    }//GEN-LAST:event_btnhome6ActionPerformed

    private void btnlogout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogout1ActionPerformed
         // TODO add your handling code here:
         MainJFrame MainFram = new MainJFrame();
         MainFram.show();
         dispose();
    }//GEN-LAST:event_btnlogout1ActionPerformed

    private void btnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookActionPerformed
        // TODO add your handling code here:
        if(txtHospital.getText().equals("") || txtPid.getText().equals("") ||txtPatientname.getText().equals("") || txtDocName.getText().equals("")|| txtdt.getText().equals("")|| txttime.getText().equals("")){
           JOptionPane .showMessageDialog(this, "Please Enter all data")  ; 
        } else{
            String data[] = {txtHospital.getText(),txtPid.getText(),txtPatientname.getText(),txtDocName.getText(),txtdt.getText(),txttime.getText()};
        
            DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
            tblModel.addRow(data);
            JOptionPane .showMessageDialog(this, "Booked successfully")  ; 
            txtHospital.setText("");
            txtPid.setText("");
            txtPatientname.setText("");
            txtDocName.setText("");
            txtdt.setText("");
            txttime.setText("");
        }
            
    }//GEN-LAST:event_btnBookActionPerformed

    private void txtHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHospitalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHospitalActionPerformed

    private void txtdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdtActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
          DefaultTableModel tblModel = (DefaultTableModel) jTable1.getModel();
        
        if(jTable1.getSelectedRowCount () == 1){
            
            tblModel.removeRow(jTable1.getSelectedRow());
            
        } else{
            if(jTable1.getRowCount () == 0){
                
                JOptionPane .showMessageDialog(this, "TABLE IS EMPTY")  ;
            }
            else{
            JOptionPane .showMessageDialog(this, "Please select any single row you want to delete")  ;
            }
        
        }
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppointmentBookingJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppointmentBookingJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppointmentBookingJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppointmentBookingJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppointmentBookingJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBook;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnhome6;
    private javax.swing.JButton btnlogout1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField txtDocName;
    private javax.swing.JTextField txtHospital;
    private javax.swing.JTextField txtPatientname;
    private javax.swing.JTextField txtPid;
    private javax.swing.JTextField txtdt;
    private javax.swing.JTextField txttime;
    // End of variables declaration//GEN-END:variables
}
