/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.util.List;
import javax.swing.JOptionPane;
import model.City;
import model.SystemAdmin;

/**
 *
 * @author shivanirahatwad
 */
public class CreateCityPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateCityPanel
     */
    SystemAdmin sysAdmin;
    public CreateCityPanel(SystemAdmin sysAdmin) {
        initComponents();
        this.sysAdmin = sysAdmin;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblCityName = new javax.swing.JLabel();
        lblCityState = new javax.swing.JLabel();
        txtCityName = new javax.swing.JTextField();
        txtCityState = new javax.swing.JTextField();
        btnSaveCity = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setText("Create City");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 62, -1, -1));

        lblCityName.setText("City Name");
        add(lblCityName, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 141, -1, -1));

        lblCityState.setText("City State");
        add(lblCityState, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 182, -1, -1));
        add(txtCityName, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 135, 150, -1));
        add(txtCityState, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 176, 150, -1));

        btnSaveCity.setBackground(new java.awt.Color(0, 153, 0));
        btnSaveCity.setText("Save City");
        btnSaveCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveCityActionPerformed(evt);
            }
        });
        add(btnSaveCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/wp2610913.jpg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveCityActionPerformed
        // TODO add your handling code here:
        List<City> cities = sysAdmin.getCities();
        City c = sysAdmin.addCity();
        String cid =  String.valueOf(cities.size() + Integer.parseInt("100"));
        String name = String.valueOf(txtCityName.getText());
        String state = String.valueOf(txtCityState.getText());
        if(name.length()==0 || state.length()==0){
            JOptionPane.showMessageDialog(this, "Enter All fields");
            return;
        }
        c.setId(cid);
        c.setState(state);
        c.setName(name);
        
        txtCityName.setText("");
        txtCityState.setText("");
        
        JOptionPane.showMessageDialog(this, "City Info Saved"); 
    }//GEN-LAST:event_btnSaveCityActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSaveCity;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblCityName;
    private javax.swing.JLabel lblCityState;
    private javax.swing.JTextField txtCityName;
    private javax.swing.JTextField txtCityState;
    // End of variables declaration//GEN-END:variables
}
