/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import model.City;
import model.Community;
import model.House;
import model.Patient;
import model.PatientDirectory;
import model.SystemAdmin;

/**
 *
 * @author shivanirahatwad
 */
public class CreatePatientPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreatePatientPanel
     */
    SystemAdmin sysAdmin;
    public CreatePatientPanel(SystemAdmin sysAdmin) {
        initComponents();
        this.sysAdmin = sysAdmin;
        populateHouses();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblpersonalDetails = new javax.swing.JLabel();
        lblPatientName = new javax.swing.JLabel();
        lblPatientAge = new javax.swing.JLabel();
        lblPatientGender = new javax.swing.JLabel();
        lblContactDetails = new javax.swing.JLabel();
        lblPatientPhoneNumber = new javax.swing.JLabel();
        lblPatientEmailAddress = new javax.swing.JLabel();
        txtPatientName = new javax.swing.JTextField();
        txtPatientAge = new javax.swing.JTextField();
        txtPatientGender = new javax.swing.JTextField();
        txtPatientPhoneNumber = new javax.swing.JTextField();
        txtPatientEmailAddress = new javax.swing.JTextField();
        lblPatientFundamentals = new javax.swing.JLabel();
        lblPatientHeight = new javax.swing.JLabel();
        lblPatientWeight = new javax.swing.JLabel();
        lblPatientAllergies = new javax.swing.JLabel();
        txtPatientHeight = new javax.swing.JTextField();
        txtPatientWeight = new javax.swing.JTextField();
        txtPatientAllergies = new javax.swing.JTextField();
        lblPatientLoginDetails = new javax.swing.JLabel();
        lblPatientUsername = new javax.swing.JLabel();
        lblPatientPassword = new javax.swing.JLabel();
        txtPatientUsername = new javax.swing.JTextField();
        txtPatientPassword = new javax.swing.JPasswordField();
        btnSavePatient = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxHouses = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblpersonalDetails.setText("Personal Details");
        add(lblpersonalDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 70, -1, -1));

        lblPatientName.setText("Name");
        add(lblPatientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 125, -1, -1));

        lblPatientAge.setText("Age");
        add(lblPatientAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 169, -1, -1));

        lblPatientGender.setText("Gender");
        add(lblPatientGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 205, -1, -1));

        lblContactDetails.setText("Contact Details");
        add(lblContactDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 298, 94, -1));

        lblPatientPhoneNumber.setText("Phone Number");
        add(lblPatientPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 346, -1, -1));

        lblPatientEmailAddress.setText("Email Address");
        add(lblPatientEmailAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 398, -1, -1));
        add(txtPatientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 122, 150, -1));
        add(txtPatientAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 166, 150, -1));
        add(txtPatientGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 202, 150, -1));

        txtPatientPhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatientPhoneNumberActionPerformed(evt);
            }
        });
        add(txtPatientPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 343, 151, -1));
        add(txtPatientEmailAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 395, 152, -1));

        lblPatientFundamentals.setText("Fundamentals");
        add(lblPatientFundamentals, new org.netbeans.lib.awtextra.AbsoluteConstraints(563, 286, -1, -1));

        lblPatientHeight.setText("Height");
        add(lblPatientHeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(502, 320, -1, -1));

        lblPatientWeight.setText("Weight");
        add(lblPatientWeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(502, 373, -1, -1));

        lblPatientAllergies.setText("Allergies");
        add(lblPatientAllergies, new org.netbeans.lib.awtextra.AbsoluteConstraints(502, 434, -1, -1));

        txtPatientHeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatientHeightActionPerformed(evt);
            }
        });
        add(txtPatientHeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(557, 317, 150, -1));
        add(txtPatientWeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(554, 370, 150, -1));
        add(txtPatientAllergies, new org.netbeans.lib.awtextra.AbsoluteConstraints(557, 428, 150, -1));

        lblPatientLoginDetails.setText("Login Details");
        add(lblPatientLoginDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(508, 70, -1, -1));

        lblPatientUsername.setText("Username");
        add(lblPatientUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(486, 125, -1, -1));

        lblPatientPassword.setText("Password");
        add(lblPatientPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(486, 166, -1, -1));
        add(txtPatientUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(563, 122, 150, -1));
        add(txtPatientPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(562, 163, 151, -1));

        btnSavePatient.setBackground(new java.awt.Color(0, 153, 0));
        btnSavePatient.setText("Save Patient");
        btnSavePatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSavePatientActionPerformed(evt);
            }
        });
        add(btnSavePatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(486, 499, 227, -1));

        jLabel1.setText("House");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 246, -1, -1));

        add(jComboBoxHouses, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 243, 150, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/wp2610913.jpg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtPatientPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatientPhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPatientPhoneNumberActionPerformed

    private void txtPatientHeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatientHeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPatientHeightActionPerformed

    private void btnSavePatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSavePatientActionPerformed
        // TODO add your handling code here:
        
        if(jComboBoxHouses.getSelectedItem()==null){
            JOptionPane.showMessageDialog(this, "Select Hospital");
            return;
        }
        House house = (House)jComboBoxHouses.getSelectedItem();
        
        String patientId = String.valueOf(sysAdmin.getPatientDirectory().patientCount() + Integer.parseInt("10000000"));
        String patientName = txtPatientName.getText();
        int patientAge;
        String patientGender = txtPatientGender.getText();
        
        String patientEmail = txtPatientEmailAddress.getText();
        String patientPhone = txtPatientPhoneNumber.getText();
        String username = txtPatientUsername.getText();
        String password = txtPatientPassword.getText();
        
        if(patientName.length()==0 || patientGender.length()==0 ||  patientEmail.length()==0 ||
                patientPhone.length()==0 || username.length()==0 || password.length()==0){
            JOptionPane.showMessageDialog(this, "Enter All Fields");
            return;
        }
        try{
            patientAge = Integer.parseInt(txtPatientAge.getText());
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Enter Valid Age");
            return;
        }
        
        
        
        String emailRegex = "^(.+)@(.+)$";
        Pattern emailPattern = Pattern.compile(emailRegex);
        Matcher emailmatcher = emailPattern.matcher(patientEmail);
        if(emailmatcher.matches()==false){
            JOptionPane.showMessageDialog(this, "Enter Valid Email");
            return;
        }
        if(patientPhone.length()!=10){
            JOptionPane.showMessageDialog(this, "Enter Valid Phone Number");
            return;
        }
        Patient p = sysAdmin.getPatientDirectory().addPatient();
        p.setPatientId(patientId);
        p.setName(patientName);
        p.setAge(patientAge);
        
        p.setGender(patientGender);
        
        p.setAddress(house);
        try{
            p.setWeightInKgs(Double.parseDouble(txtPatientWeight.getText()));
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Enter Weight in correct format");
            return;
        }
        try{
            p.setHeightIncms(Double.parseDouble(txtPatientHeight.getText()));
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Enter Height in correct format");
            return;
        }
        
        p.setAllergies(txtPatientAllergies.getText());
        
        
        
        p.setEmailAddress(patientEmail);
        p.setPhoneNumber(patientPhone);
        p.setUsername(username);
        p.setPassword(password);
        
        
        JOptionPane.showMessageDialog(this, "Patient Info Saved"); 
        
        txtPatientAge.setText("");
        txtPatientEmailAddress.setText("");
        txtPatientAllergies.setText("");
        txtPatientGender.setText("");
        txtPatientName.setText("");
        txtPatientHeight.setText("");
        txtPatientWeight.setText("");
        txtPatientPassword.setText("");
        txtPatientPhoneNumber.setText("");
        
        txtPatientUsername.setText("");
        jComboBoxHouses.setSelectedItem(null);
        
        
    }//GEN-LAST:event_btnSavePatientActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSavePatient;
    private javax.swing.JComboBox<Object> jComboBoxHouses;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblContactDetails;
    private javax.swing.JLabel lblPatientAge;
    private javax.swing.JLabel lblPatientAllergies;
    private javax.swing.JLabel lblPatientEmailAddress;
    private javax.swing.JLabel lblPatientFundamentals;
    private javax.swing.JLabel lblPatientGender;
    private javax.swing.JLabel lblPatientHeight;
    private javax.swing.JLabel lblPatientLoginDetails;
    private javax.swing.JLabel lblPatientName;
    private javax.swing.JLabel lblPatientPassword;
    private javax.swing.JLabel lblPatientPhoneNumber;
    private javax.swing.JLabel lblPatientUsername;
    private javax.swing.JLabel lblPatientWeight;
    private javax.swing.JLabel lblpersonalDetails;
    private javax.swing.JTextField txtPatientAge;
    private javax.swing.JTextField txtPatientAllergies;
    private javax.swing.JTextField txtPatientEmailAddress;
    private javax.swing.JTextField txtPatientGender;
    private javax.swing.JTextField txtPatientHeight;
    private javax.swing.JTextField txtPatientName;
    private javax.swing.JPasswordField txtPatientPassword;
    private javax.swing.JTextField txtPatientPhoneNumber;
    private javax.swing.JTextField txtPatientUsername;
    private javax.swing.JTextField txtPatientWeight;
    // End of variables declaration//GEN-END:variables

    private void populateHouses() {
        /*
        List<City> cities = sysAdmin.getCities();
        jComboBoxHouseCommunity.removeAllItems();
        for(City c : cities){
            for(Community community : c.getCommunityList()){
                jComboBoxHouseCommunity.addItem(community);
            }
        }
        */
        List<City> cities = sysAdmin.getCities();
        jComboBoxHouses.removeAllItems();
        for(City c : cities){
            for(Community community : c.getCommunityList()){
                for(House h : community.getHouseList()){
                    jComboBoxHouses.addItem(h);
                }
            }
        }
        
    }
}
