/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import java.awt.Color;

/**
 *
 * @author shivanirahatwad
 */
public class HospitalAdminLogin extends javax.swing.JFrame {

    /**
     * Creates new form HospitalAdminLoginJPanel
     */
    public HospitalAdminLogin() {
        initComponents();
        getContentPane().setBackground(Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        HospitalTxt = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        btnhome5 = new javax.swing.JButton();
        HospitalPswd = new javax.swing.JPasswordField();
        errorText = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setText("ADMIN LOGIN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel2.setText("USERNAME:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 109, -1));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel3.setText("PASSWORD:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 199, -1, -1));

        HospitalTxt.setBackground(new java.awt.Color(255, 255, 204));
        getContentPane().add(HospitalTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 164, -1));

        btnLogin.setBackground(new java.awt.Color(0, 153, 51));
        btnLogin.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnLogin.setText("LOGIN");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 279, -1, -1));

        btnhome5.setBackground(new java.awt.Color(51, 153, 255));
        btnhome5.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnhome5.setText("HOME");
        btnhome5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhome5ActionPerformed(evt);
            }
        });
        getContentPane().add(btnhome5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, 87, -1));

        HospitalPswd.setBackground(new java.awt.Color(255, 255, 204));
        getContentPane().add(HospitalPswd, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, 164, -1));

        errorText.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        errorText.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(errorText, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 326, 446, 38));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/istockphoto-1318410710-170667a.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnhome5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhome5ActionPerformed
        // TODO add your handling code here:
        MainJFrame MainFram = new MainJFrame();
         MainFram.show();
         dispose();
    }//GEN-LAST:event_btnhome5ActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        String HospitalUser = HospitalTxt.getText();
        String HospitalPasswd = HospitalPswd.getText();
        
         if (HospitalUser.equals("hospital") && HospitalPasswd.equals("hospital")) {
            
             
            HospitalHome HospitalHom = new HospitalHome();
         HospitalHom.show();
         dispose(); 
          }else {
        errorText.setText("Incorrect Credentials,Please enter correct details");
        }
        if (HospitalUser.equals("hospital1") && HospitalPasswd.equals("hospital1")) {
            
             
            HospitalHome HospitalHom = new HospitalHome();
         HospitalHom.show();
         dispose(); 
          }else {
        errorText.setText("Incorrect Credentials,Please enter correct details");
        }
          if (HospitalUser.equals("hospital2") && HospitalPasswd.equals("hospital2")) {
            
             
            HospitalHome HospitalHom = new HospitalHome();
         HospitalHom.show();
         dispose(); 
          }else {
        errorText.setText("Incorrect Credentials,Please enter correct details");
        }
        
     
        
        
        
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HospitalAdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HospitalAdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HospitalAdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HospitalAdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HospitalAdminLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField HospitalPswd;
    private javax.swing.JTextField HospitalTxt;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnhome5;
    private javax.swing.JLabel errorText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
