/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import java.awt.Color;

/**
 *
 * @author shivanirahatwad
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        
        
        getContentPane().setBackground(Color.pink);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnpatientlogin = new javax.swing.JButton();
        btndoclogin = new javax.swing.JButton();
        btnHospitalAdminlogin = new javax.swing.JButton();
        btncomadmin = new javax.swing.JButton();
        btnSystemAdmlogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 204));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setText("LOGIN AS:");
        jLabel1.setMaximumSize(new java.awt.Dimension(63, 20));
        jLabel1.setPreferredSize(new java.awt.Dimension(100, 100));
        jLabel1.setSize(new java.awt.Dimension(100, 100));

        btnpatientlogin.setText("PATIENT");
        btnpatientlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpatientloginActionPerformed(evt);
            }
        });

        btndoclogin.setText("DOCTOR");
        btndoclogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndocloginActionPerformed(evt);
            }
        });

        btnHospitalAdminlogin.setText("HOSPITAL ADMIN");
        btnHospitalAdminlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHospitalAdminloginActionPerformed(evt);
            }
        });

        btncomadmin.setText("COMMUNITY ADMIN");
        btncomadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncomadminActionPerformed(evt);
            }
        });

        btnSystemAdmlogin.setText("SYSTEM ADMIN");
        btnSystemAdmlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSystemAdmloginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(281, 281, 281)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btncomadmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHospitalAdminlogin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnpatientlogin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btndoclogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSystemAdmlogin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(258, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(btnpatientlogin)
                .addGap(18, 18, 18)
                .addComponent(btndoclogin)
                .addGap(18, 18, 18)
                .addComponent(btnHospitalAdminlogin)
                .addGap(18, 18, 18)
                .addComponent(btncomadmin)
                .addGap(18, 18, 18)
                .addComponent(btnSystemAdmlogin)
                .addContainerGap(150, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnpatientloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpatientloginActionPerformed
        // TODO add your handling code here:
        
          PatientLogin patientlog = new PatientLogin();
         patientlog.show();
         dispose();
    }//GEN-LAST:event_btnpatientloginActionPerformed

    private void btndocloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndocloginActionPerformed
        // TODO add your handling code here:
          DoctorLogin Doctorlog = new DoctorLogin();
         Doctorlog.show();
         dispose();
    }//GEN-LAST:event_btndocloginActionPerformed

    private void btncomadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncomadminActionPerformed
        // TODO add your handling code here:
        CommunityAdminLogin CommunityAdminLog = new  CommunityAdminLogin();
        CommunityAdminLog.show();
         dispose();
    }//GEN-LAST:event_btncomadminActionPerformed

    private void btnHospitalAdminloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHospitalAdminloginActionPerformed
        // TODO add your handling code here:
          HospitalAdminLogin HospitalAdminLog = new HospitalAdminLogin();
         HospitalAdminLog.show();
         dispose();
    }//GEN-LAST:event_btnHospitalAdminloginActionPerformed

    private void btnSystemAdmloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSystemAdmloginActionPerformed
        // TODO add your handling code here:
         SystemAdminLogin SystemAdminLog = new SystemAdminLogin();
         SystemAdminLog.show();
         dispose();
        
    }//GEN-LAST:event_btnSystemAdmloginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHospitalAdminlogin;
    private javax.swing.JButton btnSystemAdmlogin;
    private javax.swing.JButton btncomadmin;
    private javax.swing.JButton btndoclogin;
    private javax.swing.JButton btnpatientlogin;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
