/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Doctor;
import model.DoctorDirectory;
import model.Hospital;
import model.HospitalDirectory;
import model.SystemAdmin;

/**
 *
 * @author shivanirahatwad
 */
public class ViewDoctorPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewDoctorPanel
     */
    SystemAdmin sysAdmin;
    public ViewDoctorPanel(SystemAdmin sysAdmin) {
        initComponents();
        this.sysAdmin = sysAdmin;
        populateTable();
        populateHospitals();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDoctors = new javax.swing.JTable();
        btnViewDoctor = new javax.swing.JButton();
        btnUpdateDoctor = new javax.swing.JButton();
        txtDoctorName = new javax.swing.JTextField();
        lblPatientLoginDetails = new javax.swing.JLabel();
        txtDoctorAge = new javax.swing.JTextField();
        lblDoctorUsername = new javax.swing.JLabel();
        txtDoctorGender = new javax.swing.JTextField();
        lblContactDetails = new javax.swing.JLabel();
        lblDoctorHouse = new javax.swing.JLabel();
        txtDoctorPhoneNumber = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDoctorEmailAddress = new javax.swing.JTextField();
        txtDoctorOccupation = new javax.swing.JTextField();
        jComboBoxDoctorHospital = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        lblpersonalDetails = new javax.swing.JLabel();
        txtDoctorExperience = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lbDoctorName = new javax.swing.JLabel();
        txtDoctorSpecialisation = new javax.swing.JTextField();
        lblDoctorAge = new javax.swing.JLabel();
        lblDoctorPassword = new javax.swing.JLabel();
        txtDoctorUsername = new javax.swing.JTextField();
        lblDoctorGender = new javax.swing.JLabel();
        lblDoctorPhoneNumber = new javax.swing.JLabel();
        txtDoctorPassword = new javax.swing.JPasswordField();
        lblDoctorEmailAddress = new javax.swing.JLabel();
        btnSaveDoctor = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtDoctorId = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("View Doctors");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 6, -1, -1));

        tblDoctors.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "DoctorId", "Doctor Name", "Doctor Occupation", "Doctor Experience", "Doctor Specialisation", "Doctor Hospital"
            }
        ));
        jScrollPane1.setViewportView(tblDoctors);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 35, 825, 173));

        btnViewDoctor.setText("View Doctor");
        btnViewDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDoctorActionPerformed(evt);
            }
        });
        add(btnViewDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(524, 239, -1, -1));

        btnUpdateDoctor.setText("Update Doctors");
        btnUpdateDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateDoctorActionPerformed(evt);
            }
        });
        add(btnUpdateDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(657, 239, -1, -1));
        add(txtDoctorName, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 332, 150, -1));

        lblPatientLoginDetails.setText("Login Details");
        add(lblPatientLoginDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(544, 268, -1, -1));
        add(txtDoctorAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 376, 150, -1));

        lblDoctorUsername.setText("Username");
        add(lblDoctorUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(451, 335, -1, -1));
        add(txtDoctorGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 412, 150, -1));

        lblContactDetails.setText("Contact Details");
        add(lblContactDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 649, 94, -1));

        lblDoctorHouse.setText("Hospital");
        add(lblDoctorHouse, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 463, -1, -1));

        txtDoctorPhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDoctorPhoneNumberActionPerformed(evt);
            }
        });
        add(txtDoctorPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 672, 151, -1));

        jLabel3.setText("Occupation");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 511, -1, -1));
        add(txtDoctorEmailAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 715, 155, -1));
        add(txtDoctorOccupation, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 508, 150, -1));

        add(jComboBoxDoctorHospital, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 460, 150, -1));

        jLabel2.setText("Experience");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 560, -1, -1));

        lblpersonalDetails.setText("Personal Details");
        add(lblpersonalDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 242, -1, -1));
        add(txtDoctorExperience, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 557, 150, -1));

        jLabel4.setText("Specialisation");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 614, -1, -1));

        lbDoctorName.setText("Name");
        add(lbDoctorName, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 335, -1, -1));
        add(txtDoctorSpecialisation, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 608, 150, -1));

        lblDoctorAge.setText("Age");
        add(lblDoctorAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 379, -1, -1));

        lblDoctorPassword.setText("Password");
        add(lblDoctorPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 376, -1, -1));
        add(txtDoctorUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(544, 332, 150, -1));

        lblDoctorGender.setText("Gender");
        add(lblDoctorGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 415, -1, -1));

        lblDoctorPhoneNumber.setText("Phone Number");
        add(lblDoctorPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 678, -1, -1));
        add(txtDoctorPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(544, 373, 150, -1));

        lblDoctorEmailAddress.setText("Email Address");
        add(lblDoctorEmailAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 718, -1, -1));

        btnSaveDoctor.setText("Save Doctor");
        btnSaveDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveDoctorActionPerformed(evt);
            }
        });
        add(btnSaveDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(522, 474, 342, -1));

        jLabel5.setText("DoctorId");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 297, -1, -1));
        add(txtDoctorId, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 291, 150, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/wp2610913.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtDoctorPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDoctorPhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDoctorPhoneNumberActionPerformed

    private void btnSaveDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveDoctorActionPerformed
        // TODO add your handling code here:
        
        

        if(jComboBoxDoctorHospital.getSelectedItem()==null){
            JOptionPane.showMessageDialog(this, "Select Hospital");
            return;
        }
        Hospital hospital = (Hospital)jComboBoxDoctorHospital.getSelectedItem();
        
        Doctor d = sysAdmin.getDoctorDirectory().getDoctor(txtDoctorId.getText());
        String doctorId = txtDoctorId.getText();
        String doctorName = txtDoctorName.getText();
        int doctorAge,doctorExperience;
        String doctorGender = txtDoctorGender.getText();
        String doctorOccupation = txtDoctorOccupation.getText();

        String specialisation = txtDoctorSpecialisation.getText();
        String doctorEmail = txtDoctorEmailAddress.getText();
        String doctorPhone = txtDoctorPhoneNumber.getText();
        String username = txtDoctorUsername.getText();
        String password = txtDoctorPassword.getText();

        if(doctorName.length()==0 || doctorGender.length()==0 || doctorOccupation.length()==0 || specialisation.length()==0 || doctorEmail.length()==0 ||
            doctorPhone.length()==0 || username.length()==0 || password.length()==0){
            JOptionPane.showMessageDialog(this, "Enter All Fields");
            return;
        }
        try{
            doctorAge = Integer.parseInt(txtDoctorAge.getText());
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Enter Valid Age");
            return;
        }

        try{
            doctorExperience = Integer.parseInt(txtDoctorExperience.getText());
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Enter Valid Experience");
            return;
        }

        String emailRegex = "^(.+)@(.+)$";
        Pattern emailPattern = Pattern.compile(emailRegex);
        Matcher emailmatcher = emailPattern.matcher(doctorEmail);
        if(emailmatcher.matches()==false){
            JOptionPane.showMessageDialog(this, "Enter Valid Email");
            return;
        }
        if(doctorPhone.length()!=10){
            JOptionPane.showMessageDialog(this, "Enter Valid Phone Number");
            return;
        }

        d.setDoctorId(doctorId);
        d.setDoctorName(doctorName);
        d.setAge(doctorAge);
        d.setExperience(doctorExperience);
        d.setGender(doctorGender);
        d.setOccupation(doctorOccupation);
        d.setSpecialization(specialisation);
        d.setEmail(doctorEmail);
        d.setPhoneNumber(doctorPhone);
        d.setUsername(username);
        d.setPassword(password);
        d.setHospital(hospital);

        JOptionPane.showMessageDialog(this, "Doctor Info Updated");

        txtDoctorAge.setText("");
        txtDoctorEmailAddress.setText("");
        txtDoctorExperience.setText("");
        txtDoctorGender.setText("");
        txtDoctorName.setText("");
        txtDoctorOccupation.setText("");
        txtDoctorPassword.setText("");
        txtDoctorPhoneNumber.setText("");
        txtDoctorSpecialisation.setText("");
        txtDoctorUsername.setText("");
        jComboBoxDoctorHospital.setSelectedItem(null);
        populateTable();

    }//GEN-LAST:event_btnSaveDoctorActionPerformed

    private void btnViewDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDoctorActionPerformed
        // TODO add your handling code here:
        
        int selectedrowIndex = tblDoctors.getSelectedRow();
        if(selectedrowIndex < 0){
            JOptionPane.showMessageDialog(this, "Please select row to view the details");
            return;
        }
        
        DefaultTableModel model = (DefaultTableModel) tblDoctors.getModel();
        Doctor d = (Doctor) model.getValueAt(selectedrowIndex, 1);
        
        txtDoctorId.setText(String.valueOf(d.getDoctorId()));
        txtDoctorId.setEditable(false);
        txtDoctorName.setText(d.getDoctorName());
        txtDoctorName.setEditable(false);
        txtDoctorAge.setText(String.valueOf(d.getAge()));
        txtDoctorAge.setEditable(false);
        txtDoctorGender.setText(String.valueOf(d.getGender()));
        txtDoctorGender.setEditable(false);
        jComboBoxDoctorHospital.setSelectedItem(d.getHospital());
        jComboBoxDoctorHospital.setEditable(false);
        txtDoctorOccupation.setText(d.getOccupation());
        txtDoctorOccupation.setEditable(false);
        txtDoctorExperience.setText(String.valueOf(d.getExperience()));
        txtDoctorExperience.setEditable(false);
        txtDoctorSpecialisation.setText(d.getSpecialization());
        txtDoctorSpecialisation.setEditable(false);
        txtDoctorPhoneNumber.setText(d.getPhoneNumber());
        txtDoctorPhoneNumber.setEditable(false);
        txtDoctorEmailAddress.setText(d.getEmail());
        txtDoctorEmailAddress.setEditable(false);
        txtDoctorUsername.setText(d.getUsername());
        txtDoctorUsername.setEditable(false);
        txtDoctorPassword.setText(d.getPassword());
        txtDoctorPassword.setEditable(false);
        
    }//GEN-LAST:event_btnViewDoctorActionPerformed

    private void btnUpdateDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateDoctorActionPerformed
        // TODO add your handling code here:
        int selectedrowIndex = tblDoctors.getSelectedRow();
        if(selectedrowIndex < 0){
            JOptionPane.showMessageDialog(this, "Please select row to view the details");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblDoctors.getModel();
        Doctor d = (Doctor) model.getValueAt(selectedrowIndex, 1);
        
        txtDoctorId.setText(String.valueOf(d.getDoctorId()));
        txtDoctorId.setEditable(false);
        txtDoctorName.setText(d.getDoctorName());
        txtDoctorName.setEditable(true);
        txtDoctorAge.setText(String.valueOf(d.getAge()));
        txtDoctorAge.setEditable(true);
        txtDoctorGender.setText(String.valueOf(d.getGender()));
        txtDoctorGender.setEditable(true);
        jComboBoxDoctorHospital.setSelectedItem(d.getHospital());
        jComboBoxDoctorHospital.setEditable(true);
        txtDoctorOccupation.setText(d.getOccupation());
        txtDoctorOccupation.setEditable(true);
        txtDoctorExperience.setText(String.valueOf(d.getExperience()));
        txtDoctorExperience.setEditable(true);
        txtDoctorSpecialisation.setText(d.getSpecialization());
        txtDoctorSpecialisation.setEditable(true);
        txtDoctorPhoneNumber.setText(d.getPhoneNumber());
        txtDoctorPhoneNumber.setEditable(true);
        txtDoctorEmailAddress.setText(d.getEmail());
        txtDoctorEmailAddress.setEditable(true);
        txtDoctorUsername.setText(d.getUsername());
        txtDoctorUsername.setEditable(true);
        txtDoctorPassword.setText(d.getPassword());
        txtDoctorPassword.setEditable(true);
    }//GEN-LAST:event_btnUpdateDoctorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSaveDoctor;
    private javax.swing.JButton btnUpdateDoctor;
    private javax.swing.JButton btnViewDoctor;
    private javax.swing.JComboBox<Object> jComboBoxDoctorHospital;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbDoctorName;
    private javax.swing.JLabel lblContactDetails;
    private javax.swing.JLabel lblDoctorAge;
    private javax.swing.JLabel lblDoctorEmailAddress;
    private javax.swing.JLabel lblDoctorGender;
    private javax.swing.JLabel lblDoctorHouse;
    private javax.swing.JLabel lblDoctorPassword;
    private javax.swing.JLabel lblDoctorPhoneNumber;
    private javax.swing.JLabel lblDoctorUsername;
    private javax.swing.JLabel lblPatientLoginDetails;
    private javax.swing.JLabel lblpersonalDetails;
    private javax.swing.JTable tblDoctors;
    private javax.swing.JTextField txtDoctorAge;
    private javax.swing.JTextField txtDoctorEmailAddress;
    private javax.swing.JTextField txtDoctorExperience;
    private javax.swing.JTextField txtDoctorGender;
    private javax.swing.JTextField txtDoctorId;
    private javax.swing.JTextField txtDoctorName;
    private javax.swing.JTextField txtDoctorOccupation;
    private javax.swing.JPasswordField txtDoctorPassword;
    private javax.swing.JTextField txtDoctorPhoneNumber;
    private javax.swing.JTextField txtDoctorSpecialisation;
    private javax.swing.JTextField txtDoctorUsername;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        
        DefaultTableModel model = (DefaultTableModel) tblDoctors.getModel();
        model.setRowCount(0);
        DoctorDirectory dd = sysAdmin.getDoctorDirectory();
        List<Doctor> doctors = dd.getDoctorDirectory();
        for(Doctor d : doctors){
            Object[] row = new Object[6];
            row[0] = d.getDoctorId();
            row[1] = d;
            row[2] = d.getOccupation();
            row[3] = d.getExperience();
            row[4] = d.getSpecialization();
            row[5] = d.getHospital();
            model.addRow(row);
        }
        
    }

    private void populateHospitals() {
        /*
        List<City> cities = sysAdmin.getCities();
        jComboBoxHospitalCommunity.removeAllItems();
        for(City c : cities){
            for(Community community : c.getCommunityList()){
                jComboBoxHospitalCommunity.addItem(community);
            }
        }
        */
        HospitalDirectory hd = sysAdmin.getHospitalDirectory();
        List<Hospital> hl = hd.getHospitalDirectory();
        for(Hospital h : hl){
            jComboBoxDoctorHospital.addItem(h);
        }
        
    }
}
