/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.Community;
import model.Doctor;
import model.DoctorDirectory;
import model.Patient;
import model.SystemAdmin;

/**
 *
 * @author shivanirahatwad
 */
public class ViewDoctorsPatientPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewDoctorsPatientPanel
     */
    SystemAdmin sysAdmin;
    Patient p;
    public ViewDoctorsPatientPanel(SystemAdmin sysAdmin,Patient p) {
        initComponents();
        this.sysAdmin = sysAdmin;
        this.p = p;
        populateTable();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDoctorsList = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("View Doctors Near You");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 39, -1, -1));

        tblDoctorsList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Doctor", "Hospital", "Community", "Speciality"
            }
        ));
        jScrollPane1.setViewportView(tblDoctorsList);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 96, 777, 166));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/wp2610913.jpg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDoctorsList;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        
        DefaultTableModel model = (DefaultTableModel) tblDoctorsList.getModel();
        model.setRowCount(0);
        Community patientCommunity = p.getAddress().getCommunity();
        DoctorDirectory dd = sysAdmin.getDoctorDirectory();
        List<Doctor> dl = dd.getDoctorDirectory();
        for(Doctor d : dl){
            if(d.getHospital().getCommunity().getCommunityId().equals(patientCommunity.getCommunityId())){
                Object[] row = new Object[4];
                row[0] = d;
                row[1] = d.getHospital();
                row[2] = d.getHospital().getCommunity();
                row[3] = d.getSpecialization();
                model.addRow(row);
            }
        }
        
        
    }
}
