/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.Person;

import business.Person;
import business.PersonDirectory;
import java.awt.CardLayout;
import java.awt.event.KeyEvent;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author shivanirahatwad
 */
public class CreatePersonJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreatePersonJPanel
     */
    
    private PersonDirectory personDirectory;
    private JPanel userContainer;
    private ManagePersonJPanel mngJPanel;
    
    public CreatePersonJPanel(JPanel userContainer,PersonDirectory personDirectory) {
        initComponents();
        this.personDirectory = personDirectory;
        this.userContainer = userContainer;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblHouseAddress = new javax.swing.JLabel();
        lblCommunity = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        txtPersonName = new javax.swing.JTextField();
        txtHouseAddress = new javax.swing.JTextField();
        txtCommunity = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        lblCity1 = new javax.swing.JLabel();
        txtZipcode = new javax.swing.JTextField();
        lblAge1 = new javax.swing.JLabel();
        radioBtnFemale = new javax.swing.JRadioButton();
        radioBtnMale = new javax.swing.JRadioButton();
        btnGoBack = new javax.swing.JButton();
        lblPersonNameError = new javax.swing.JLabel();
        lblPersonAgeError = new javax.swing.JLabel();
        lblZipcodeError = new javax.swing.JLabel();
        lblCommunityError = new javax.swing.JLabel();
        lblCityError = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Add Person Details");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 22, 351, 61));

        lblAge.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAge.setText("Age:");
        add(lblAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 158, 155, 25));

        lblName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblName.setText("Name:");
        add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 110, 155, 25));

        lblHouseAddress.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblHouseAddress.setText("House Address:");
        add(lblHouseAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 258, 155, 25));

        lblCommunity.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCommunity.setText("Community:");
        add(lblCommunity, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 304, 155, 25));

        lblCity.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCity.setText("Zip Code:");
        add(lblCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 402, 155, 25));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 463, 90, 31));

        txtPersonName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPersonNameActionPerformed(evt);
            }
        });
        txtPersonName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPersonNameKeyPressed(evt);
            }
        });
        add(txtPersonName, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 110, 218, 30));
        add(txtHouseAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 256, 218, 30));

        txtCommunity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCommunityKeyPressed(evt);
            }
        });
        add(txtCommunity, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 304, 218, 30));

        txtAge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAgeKeyPressed(evt);
            }
        });
        add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 160, 218, 30));

        txtCity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCityKeyPressed(evt);
            }
        });
        add(txtCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 352, 218, 30));

        lblCity1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCity1.setText("City:");
        add(lblCity1, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 352, 155, 25));

        txtZipcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtZipcodeKeyPressed(evt);
            }
        });
        add(txtZipcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 400, 218, 30));

        lblAge1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAge1.setText("Gender:");
        add(lblAge1, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 208, 155, 25));

        buttonGroup.add(radioBtnFemale);
        radioBtnFemale.setText("Male");
        add(radioBtnFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 208, -1, -1));

        buttonGroup.add(radioBtnMale);
        radioBtnMale.setText("Female");
        add(radioBtnMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 208, -1, -1));

        btnGoBack.setText("<< Go Back");
        btnGoBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoBackActionPerformed(evt);
            }
        });
        add(btnGoBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 463, 102, 31));
        add(lblPersonNameError, new org.netbeans.lib.awtextra.AbsoluteConstraints(526, 110, 190, 30));
        add(lblPersonAgeError, new org.netbeans.lib.awtextra.AbsoluteConstraints(526, 160, 190, 30));
        add(lblZipcodeError, new org.netbeans.lib.awtextra.AbsoluteConstraints(526, 400, 190, 30));
        add(lblCommunityError, new org.netbeans.lib.awtextra.AbsoluteConstraints(526, 304, 190, 30));
        add(lblCityError, new org.netbeans.lib.awtextra.AbsoluteConstraints(526, 352, 190, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userInterface/Person/wp2610913.jpg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
     
        if (checkBlankInput()==Boolean.TRUE)
        {
            String personName= txtPersonName.getText();
            int age= Integer.parseInt(txtAge.getText());
            String houseAddress = txtHouseAddress.getText();
            String community = txtCommunity.getText();
            String city = txtCity.getText();
            int zipcode = Integer.parseInt(txtZipcode.getText());
            
            
            String charPattern = "^[a-zA-z]+";
            Pattern expPersonName = Pattern.compile(charPattern);

            String agePattern = "^[0-9]{2}+";
            Pattern expAge = Pattern.compile(agePattern);
            
            String zipcodePattern = "^[0-9]{5}+";
            Pattern expZipCode = Pattern.compile(zipcodePattern);
            
            Matcher matcherPersonName = expPersonName.matcher(txtPersonName.getText());
            if(!matcherPersonName.matches()){
                lblPersonNameError.setText("Enter a valid person name!!");
            }else{
                lblPersonNameError.setText(" ");
                Matcher matchNumber = expAge.matcher(txtAge.getText());
                if(!matchNumber.matches()){
                        lblPersonAgeError.setText("Enter a valid Age!!");
                }else{
                    lblPersonAgeError.setText(" ");
                    Matcher matchZipCode = expZipCode.matcher(txtZipcode.getText());
                    if(!matchZipCode.matches()){
                            lblZipcodeError.setText("Enter a valid Zipcode!!");
                    }else{
                        lblZipcodeError.setText(" ");
                        Matcher matchCity = expPersonName.matcher(txtCity.getText());
                        if(!matchCity.matches()){
                            lblCityError.setText("Enter a valid City!!");
                        }else{
                            lblCityError.setText(" ");
                            Matcher macthCommunity = expPersonName.matcher(txtCommunity.getText());
                            if(!macthCommunity.matches()){
                            lblCommunityError.setText("Enter a valid Community!!");
                            }else{
                                lblCommunityError.setText(" ");
                                Person person=personDirectory.addNewPerson();
                                person.setPersonName(personName);
                                person.setAge(age);
                                person.setHouseAddress(houseAddress);
                                person.setCommunity(community);
                                person.setCity(city);
                                person.setZipcode(zipcode);

                               if(radioBtnFemale.isSelected()){
                                    person.setGender(radioBtnFemale.getText());
                                }else {
                                    person.setGender(radioBtnMale.getText());
                                }
                                JOptionPane.showMessageDialog(this, "Person added!!", "Update",
                                        JOptionPane.INFORMATION_MESSAGE);
                                clearFields();
                                
                            }
                        }
                    }
                    
                }
                
            }
           
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Please enter all values",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnGoBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoBackActionPerformed
        // TODO add your handling code here:
        
        userContainer.remove(this);
        CardLayout layout = (CardLayout) userContainer.getLayout();
        layout.previous(userContainer);
        
    }//GEN-LAST:event_btnGoBackActionPerformed

    private void txtPersonNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPersonNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPersonNameActionPerformed

    private void txtPersonNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPersonNameKeyPressed
        // TODO add your handling code here:
        
        char c =evt.getKeyChar();
           
           if(Character.isLetter(c) || Character.isWhitespace(c)|| Character.isISOControl(c)){
               lblPersonNameError.setText(" ");
               txtPersonName.setEditable(true);
               
           }else {
               if(!Character.isLetter(c)){
              // txtName.setEditable(false);
                lblPersonNameError.setText("Enter a valid name");
               }
           }
    }//GEN-LAST:event_txtPersonNameKeyPressed

    private void txtAgeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAgeKeyPressed
        // TODO add your handling code here:
        
        String serialNumber = txtAge.getText();
        int length = serialNumber.length();
        
        char c = evt.getKeyChar();
        
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
            if(length<2){
                txtAge.setEditable(true);
                lblPersonAgeError.setText("Age should be 2 digits!!");
            }else{
                txtAge.setEditable(false);
                lblPersonAgeError.setText(" ");
            }
        }else{
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE){
                txtAge.setEditable(true);
               
            }else{
                txtAge.setEditable(false);  
            }
        }
    }//GEN-LAST:event_txtAgeKeyPressed

    private void txtZipcodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtZipcodeKeyPressed
        // TODO add your handling code here:
        
        String serialNumber = txtZipcode.getText();
        int length = serialNumber.length();
        
        char c = evt.getKeyChar();
        
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
            if(length<5){
                txtZipcode.setEditable(true);
                lblZipcodeError.setText("Zipcode Number should be 5 digits!!");
            }else{
                txtZipcode.setEditable(false);
                lblZipcodeError.setText(" ");
            }
        }else{
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE){
                txtZipcode.setEditable(true);
               
            }else{
                txtZipcode.setEditable(false);  
            }
        }
    }//GEN-LAST:event_txtZipcodeKeyPressed

    private void txtCityKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCityKeyPressed
        // TODO add your handling code here:
        char c =evt.getKeyChar();
           
           if(Character.isLetter(c) || Character.isWhitespace(c)|| Character.isISOControl(c)){
               lblCityError.setText(" ");
               txtCity.setEditable(true);
               
           }else {
               if(!Character.isLetter(c)){
              // txtName.setEditable(false);
                lblCityError.setText("Enter a valid City");
               }
           }
        
    }//GEN-LAST:event_txtCityKeyPressed

    private void txtCommunityKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCommunityKeyPressed
        // TODO add your handling code here:
            
           char c =evt.getKeyChar();
           
           if(Character.isLetter(c) || Character.isWhitespace(c)|| Character.isISOControl(c)){
               lblCommunityError.setText(" ");
               txtCommunity.setEditable(true);
               
           }else {
               if(!Character.isLetter(c)){
              // txtName.setEditable(false);
                lblCommunityError.setText("Enter a valid Community");
               }
           }
    }//GEN-LAST:event_txtCommunityKeyPressed

    
    private void clearFields()
    {
        txtPersonName.setText("");
        txtAge.setText("");
        buttonGroup.clearSelection();
        txtHouseAddress.setText("");
        txtCommunity.setText("");
        txtCity.setText("");
        txtZipcode.setText("");
    }
    
    private Boolean checkBlankInput()
    {
        if(txtPersonName.getText().isEmpty() || txtAge.getText().isEmpty() || txtHouseAddress.getText().isEmpty() || txtCommunity.getText().isEmpty() || txtCity.getText().isEmpty() 
                || txtZipcode.getText().isEmpty())
        {
            return false;
        }
        else{
            return true;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGoBack;
    private javax.swing.JButton btnSave;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblAge1;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblCity1;
    private javax.swing.JLabel lblCityError;
    private javax.swing.JLabel lblCommunity;
    private javax.swing.JLabel lblCommunityError;
    private javax.swing.JLabel lblHouseAddress;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPersonAgeError;
    private javax.swing.JLabel lblPersonNameError;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblZipcodeError;
    private javax.swing.JRadioButton radioBtnFemale;
    private javax.swing.JRadioButton radioBtnMale;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtCommunity;
    private javax.swing.JTextField txtHouseAddress;
    private javax.swing.JTextField txtPersonName;
    private javax.swing.JTextField txtZipcode;
    // End of variables declaration//GEN-END:variables
}
