/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.Person;

import business.Person;
import business.VitalSign;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author shivanirahatwad
 */
public class ViewUpdateVitalSignsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewUpdateVitalSignsJPanel
     */
    
    private VitalSign vitalSign;
    private JPanel userContainer;
    private Person person;
    private Boolean isEdit = Boolean.FALSE;
    
    public ViewUpdateVitalSignsJPanel(JPanel jpanel, VitalSign vitalSign, Boolean isEdit) {
        initComponents();
        this.userContainer = jpanel;
        this.vitalSign = vitalSign;
        this.isEdit = isEdit;
        
        populateVitalSignDetails();
        modifyTextFields(this.isEdit);
        
        if(isEdit){
            btnUpdateVitalSign.setEnabled(true);
        }else
            btnUpdateVitalSign.setEnabled(false);
    }
    
    private void populateVitalSignDetails() {
       
        txtRespiratoryRate.setText(String.valueOf(vitalSign.getRespiratoryRate()));
        txtHeartRate.setText(String.valueOf(vitalSign.getHeartRate()));
        txtBloodPressure.setText(String.valueOf(vitalSign.getBloodPressure()));
        txtWeight.setText(String.valueOf(vitalSign.getWeight()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWeight = new javax.swing.JLabel();
        lblBloodPressure = new javax.swing.JLabel();
        lblHeartRate = new javax.swing.JLabel();
        lblRespiratoryRate = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnGoBack = new javax.swing.JButton();
        btnUpdateVitalSign = new javax.swing.JButton();
        txtWeight = new javax.swing.JTextField();
        txtBloodPressure = new javax.swing.JTextField();
        txtHeartRate = new javax.swing.JTextField();
        txtRespiratoryRate = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblWeight.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblWeight.setText("Weight in Pounds :");
        add(lblWeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 325, 174, 25));

        lblBloodPressure.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblBloodPressure.setText("Systolic Blood Pressure:");
        add(lblBloodPressure, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 269, 174, 25));

        lblHeartRate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblHeartRate.setText("Heart Rate :");
        add(lblHeartRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 214, 174, 25));

        lblRespiratoryRate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblRespiratoryRate.setText("Respiratory Rate :");
        add(lblRespiratoryRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 158, 174, 25));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("View/Update Patient Vitals Sign");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 39, 258, 48));

        btnGoBack.setText("<< Go Back");
        btnGoBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoBackActionPerformed(evt);
            }
        });
        add(btnGoBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 403, -1, 36));

        btnUpdateVitalSign.setText("Update");
        btnUpdateVitalSign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateVitalSignActionPerformed(evt);
            }
        });
        add(btnUpdateVitalSign, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 403, 115, 36));

        txtWeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWeightActionPerformed(evt);
            }
        });
        add(txtWeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 325, 234, 25));

        txtBloodPressure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBloodPressureActionPerformed(evt);
            }
        });
        add(txtBloodPressure, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 269, 234, 25));

        txtHeartRate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHeartRateActionPerformed(evt);
            }
        });
        add(txtHeartRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 214, 234, 25));

        txtRespiratoryRate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRespiratoryRateActionPerformed(evt);
            }
        });
        add(txtRespiratoryRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 158, 234, 25));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userInterface/Person/wp2610913.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateVitalSignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateVitalSignActionPerformed
        // TODO add your handling code here:
        try {
            double respiratoryRate = Integer.parseInt(txtRespiratoryRate.getText());
            double heartRate = Integer.parseInt(txtHeartRate.getText());
            double bloodPressure = Integer.parseInt(txtBloodPressure.getText());
            double weight = Integer.parseInt(txtWeight.getText());
            vitalSign.setRespiratoryRate(respiratoryRate);
            vitalSign.setHeartRate(heartRate);
            vitalSign.setBloodPressure(bloodPressure);
            vitalSign.setWeight(weight);
            /*Set current date and time as TimeStamp*/
            vitalSign.setTimestamp(new Date());
            JOptionPane.showMessageDialog(this, "Vital signs updated!!", "Update", 
                    JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Please enter correct values", 
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
        modifyTextFields(false);

    }//GEN-LAST:event_btnUpdateVitalSignActionPerformed

    private void modifyTextFields(Boolean isEdit) {
       
        if (isEdit) {
            txtRespiratoryRate.setEnabled(true);
            txtHeartRate.setEnabled(true);
            txtBloodPressure.setEnabled(true);
            txtWeight.setEnabled(true);
        } else {
            txtRespiratoryRate.setEnabled(false);
            txtHeartRate.setEnabled(false);
            txtBloodPressure.setEnabled(false);
            txtWeight.setEnabled(false);
        }
    }
    
    private void txtWeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWeightActionPerformed

    private void txtBloodPressureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBloodPressureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBloodPressureActionPerformed

    private void txtHeartRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHeartRateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHeartRateActionPerformed

    private void txtRespiratoryRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRespiratoryRateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRespiratoryRateActionPerformed

    private void btnGoBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoBackActionPerformed
        // TODO add your handling code here:
        
        userContainer.remove(this);
        CardLayout layout = (CardLayout) userContainer.getLayout();
        layout.previous(userContainer);
    }//GEN-LAST:event_btnGoBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGoBack;
    private javax.swing.JButton btnUpdateVitalSign;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblBloodPressure;
    private javax.swing.JLabel lblHeartRate;
    private javax.swing.JLabel lblRespiratoryRate;
    private javax.swing.JLabel lblWeight;
    private javax.swing.JTextField txtBloodPressure;
    private javax.swing.JTextField txtHeartRate;
    private javax.swing.JTextField txtRespiratoryRate;
    private javax.swing.JTextField txtWeight;
    // End of variables declaration//GEN-END:variables
}
