/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.Person;

import business.Person;
import business.PersonDirectory;
import java.awt.CardLayout;
import java.awt.event.KeyEvent;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author shivanirahatwad
 */
public class ViewUpdatePersonDetailsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewUpdatePersonDetailsJPanel
     */
    private Person person;
    private JPanel userContainer;
    private Boolean isEdit = Boolean.FALSE;
    private ManagePersonJPanel managePersonJPanel;
    
    private PersonDirectory personDirectory;
    
    public ViewUpdatePersonDetailsJPanel(JPanel userContainer, Person person, Boolean isEdit) {
        initComponents();
        this.userContainer = userContainer;
        this.person = person;
        this.isEdit = isEdit;
        populatePersonDetails();
        modifyTextFields(this.isEdit);
        
        if(isEdit){
            btnUpdatePerson.setEnabled(true);
        }else
            btnUpdatePerson.setEnabled(false);
    }

    private void populatePersonDetails() {
        //JOptionPane.showMessageDialog(this, person.toString());
        txtPersonId.setText(String.valueOf(person.getPersonId()));
        txtPersonName.setText(person.getPersonName());
        txtAge.setText(String.valueOf(person.getAge()));
        txtCommunity.setText(person.getCommunity());
        txtHouseAddress.setText(person.getHouseAddress());
        txtCity.setText(person.getCity());
        txtZipcode.setText(String.valueOf(person.getZipcode()));
        if(person.getGender() == "Male" ){
           radioBtnMale.setSelected(false);
           radioBtnFemale.setSelected(true);
       }else {
           radioBtnFemale.setSelected(false);
           radioBtnMale.setSelected(true);
       }
    }
    
    
     private void modifyTextFields(Boolean isEdit) {
      
        if (isEdit) {
            txtPersonName.setEnabled(true);
            txtAge.setEnabled(true);
            txtHouseAddress.setEnabled(true);
            txtCommunity.setEnabled(true);
            txtCity.setEnabled(true);
            txtZipcode.setEnabled(true);
            radioBtnFemale.setEnabled(true);
            radioBtnMale.setEnabled(true);
        } else {
            txtPersonName.setEnabled(false);
            txtAge.setEnabled(false);
            txtHouseAddress.setEnabled(false);
            txtCommunity.setEnabled(false);
            txtCity.setEnabled(false);
            txtZipcode.setEnabled(false);
            radioBtnFemale.setEnabled(false);
            radioBtnMale.setEnabled(false);
            
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        radioBtnFemale = new javax.swing.JRadioButton();
        lblCity = new javax.swing.JLabel();
        radioBtnMale = new javax.swing.JRadioButton();
        txtPersonName = new javax.swing.JTextField();
        txtHouseAddress = new javax.swing.JTextField();
        txtCommunity = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        lblAge = new javax.swing.JLabel();
        lblCity1 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        txtZipcode = new javax.swing.JTextField();
        lblHouseAddress = new javax.swing.JLabel();
        lblAge1 = new javax.swing.JLabel();
        lblCommunity = new javax.swing.JLabel();
        btnGoBack = new javax.swing.JButton();
        btnUpdatePerson = new javax.swing.JButton();
        lblPersonId = new javax.swing.JLabel();
        txtPersonId = new javax.swing.JTextField();
        lblPersonNameError = new javax.swing.JLabel();
        lblPersonAgeError = new javax.swing.JLabel();
        lblCommunityError = new javax.swing.JLabel();
        lblCityError = new javax.swing.JLabel();
        lblZipcodeError = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup.add(radioBtnFemale);
        radioBtnFemale.setText("Male");
        radioBtnFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnFemaleActionPerformed(evt);
            }
        });
        add(radioBtnFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 240, -1, -1));

        lblCity.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCity.setText("Zip Code:");
        add(lblCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 427, 155, 25));

        buttonGroup.add(radioBtnMale);
        radioBtnMale.setText("Female");
        add(radioBtnMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 240, -1, -1));

        txtPersonName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPersonNameKeyPressed(evt);
            }
        });
        add(txtPersonName, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 142, 218, 30));
        add(txtHouseAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 288, 218, 30));

        txtCommunity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCommunityKeyPressed(evt);
            }
        });
        add(txtCommunity, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 336, 218, 30));

        txtAge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAgeKeyPressed(evt);
            }
        });
        add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 192, 218, 30));

        lblTitle.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("View/Update Person Details");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 31, 351, 47));

        txtCity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCityKeyPressed(evt);
            }
        });
        add(txtCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 384, 218, 30));

        lblAge.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAge.setText("Age:");
        add(lblAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 190, 155, 25));

        lblCity1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCity1.setText("City:");
        add(lblCity1, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 384, 155, 25));

        lblName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblName.setText("Name:");
        add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 142, 155, 25));

        txtZipcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtZipcodeKeyPressed(evt);
            }
        });
        add(txtZipcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 432, 218, 30));

        lblHouseAddress.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblHouseAddress.setText("House Address:");
        add(lblHouseAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 290, 155, 25));

        lblAge1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAge1.setText("Gender:");
        add(lblAge1, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 240, 155, 25));

        lblCommunity.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCommunity.setText("Community:");
        add(lblCommunity, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 336, 155, 25));

        btnGoBack.setText("<< Go Back");
        btnGoBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoBackActionPerformed(evt);
            }
        });
        add(btnGoBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 499, 104, 31));

        btnUpdatePerson.setText("Update");
        btnUpdatePerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdatePersonActionPerformed(evt);
            }
        });
        add(btnUpdatePerson, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 499, 85, 31));

        lblPersonId.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPersonId.setText("Person Id:");
        add(lblPersonId, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 101, 181, 23));

        txtPersonId.setEnabled(false);
        add(txtPersonId, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 96, 218, 26));
        add(lblPersonNameError, new org.netbeans.lib.awtextra.AbsoluteConstraints(587, 142, 171, 26));
        add(lblPersonAgeError, new org.netbeans.lib.awtextra.AbsoluteConstraints(587, 192, 171, 26));
        add(lblCommunityError, new org.netbeans.lib.awtextra.AbsoluteConstraints(587, 336, 171, 26));
        add(lblCityError, new org.netbeans.lib.awtextra.AbsoluteConstraints(587, 384, 171, 26));
        add(lblZipcodeError, new org.netbeans.lib.awtextra.AbsoluteConstraints(587, 432, 171, 26));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userInterface/Person/wp2610913.jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void clearFields()
    {
        txtPersonName.setText("");
        txtAge.setText("");
        buttonGroup.clearSelection();
        txtHouseAddress.setText("");
        txtCommunity.setText("");
        txtCity.setText("");
        txtZipcode.setText("");
    }
    
    private Boolean checkBlankInput()
    {
        if(txtPersonName.getText().isEmpty() || txtAge.getText().isEmpty() || txtHouseAddress.getText().isEmpty() || txtCommunity.getText().isEmpty() || txtCity.getText().isEmpty() 
                || txtZipcode.getText().isEmpty())
        {
            return false;
        }
        else{
            return true;
        }
    }
    
    private void radioBtnFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnFemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioBtnFemaleActionPerformed

    private void btnUpdatePersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdatePersonActionPerformed
        // TODO add your handling code here:
        
    if (checkBlankInput()==Boolean.TRUE)
        {
            String personName= txtPersonName.getText();
            int age= Integer.parseInt(txtAge.getText());
            String houseAddress = txtHouseAddress.getText();
            String community = txtCommunity.getText();
            String city = txtCity.getText();
            int zipcode = Integer.parseInt(txtZipcode.getText());
            
            
            String charPattern = "^[a-zA-z]+";
            Pattern expPersonName = Pattern.compile(charPattern);

            String agePattern = "^[0-9]{2}+";
            Pattern expAge = Pattern.compile(agePattern);
            
            String zipcodePattern = "^[0-9]{5}+";
            Pattern expZipCode = Pattern.compile(zipcodePattern);
            
            Matcher matcherPersonName = expPersonName.matcher(txtPersonName.getText());
            if(!matcherPersonName.matches()){
                lblPersonNameError.setText("Enter a valid person name!!");
            }else{
                lblPersonNameError.setText(" ");
                Matcher matchNumber = expAge.matcher(txtAge.getText());
                if(!matchNumber.matches()){
                        lblPersonAgeError.setText("Enter a valid Age!!");
                }else{
                    lblPersonAgeError.setText(" ");
                    Matcher matchZipCode = expZipCode.matcher(txtZipcode.getText());
                    if(!matchZipCode.matches()){
                            lblZipcodeError.setText("Enter a valid Zipcode!!");
                    }else{
                        lblZipcodeError.setText(" ");
                        Matcher matchCity = expPersonName.matcher(txtCity.getText());
                        if(!matchCity.matches()){
                            lblCityError.setText("Enter a valid City!!");
                        }else{
                            lblCityError.setText(" ");
                            Matcher macthCommunity = expPersonName.matcher(txtCommunity.getText());
                            if(!macthCommunity.matches()){
                            lblCommunityError.setText("Enter a valid Community!!");
                            }else{
                                lblCommunityError.setText(" ");
                                
                                person.setPersonName(personName);
                                person.setAge(age);
                                person.setHouseAddress(houseAddress);
                                person.setCommunity(community);
                                person.setCity(city);
                                person.setZipcode(zipcode);

                               if(radioBtnFemale.isSelected()){
                                    person.setGender(radioBtnFemale.getText());
                                }else {
                                    person.setGender(radioBtnMale.getText());
                                }
                                JOptionPane.showMessageDialog(this, "Person Update!!", "Update",
                                        JOptionPane.INFORMATION_MESSAGE);
                                clearFields();
                                
                            }
                        }
                    }
                    
                }
                
            }
        }
    
        else
        {
            JOptionPane.showMessageDialog(this, "Please enter all values",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUpdatePersonActionPerformed

    private void btnGoBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoBackActionPerformed
        // TODO add your handling code here:
        
        
        userContainer.remove(this);
        CardLayout layout = (CardLayout) userContainer.getLayout();
        layout.previous(userContainer);
    }//GEN-LAST:event_btnGoBackActionPerformed

    private void txtPersonNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPersonNameKeyPressed
        // TODO add your handling code here:
        
         char c =evt.getKeyChar();
           
           if(Character.isLetter(c) || Character.isWhitespace(c)|| Character.isISOControl(c)){
               lblPersonNameError.setText(" ");
               txtPersonName.setEditable(true);
               
           }else {
               if(!Character.isLetter(c)){
              // txtName.setEditable(false);
                lblPersonNameError.setText("Enter a valid name");
               }
           }
    }//GEN-LAST:event_txtPersonNameKeyPressed

    private void txtAgeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAgeKeyPressed
        // TODO add your handling code here:
        
        String serialNumber = txtAge.getText();
        int length = serialNumber.length();
        
        char c = evt.getKeyChar();
        
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
            if(length<2){
                txtAge.setEditable(true);
                lblPersonAgeError.setText("Age should be 2 digits!!");
            }else{
                txtAge.setEditable(false);
                lblPersonAgeError.setText(" ");
            }
        }else{
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE){
                txtAge.setEditable(true);
               
            }else{
                txtAge.setEditable(false);  
            }
        }
        
    }//GEN-LAST:event_txtAgeKeyPressed

    private void txtZipcodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtZipcodeKeyPressed
        // TODO add your handling code here:
        
        
        String serialNumber = txtZipcode.getText();
        int length = serialNumber.length();
        
        char c = evt.getKeyChar();
        
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
            if(length<5){
                txtZipcode.setEditable(true);
                lblZipcodeError.setText("Zipcode Number should be 5 digits!!");
            }else{
                txtZipcode.setEditable(false);
                lblZipcodeError.setText(" ");
            }
        }else{
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE){
                txtZipcode.setEditable(true);
               
            }else{
                txtZipcode.setEditable(false);  
            }
        }
    }//GEN-LAST:event_txtZipcodeKeyPressed

    private void txtCityKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCityKeyPressed
        // TODO add your handling code here:
        char c =evt.getKeyChar();
           
           if(Character.isLetter(c) || Character.isWhitespace(c)|| Character.isISOControl(c)){
               lblCityError.setText(" ");
               txtCity.setEditable(true);
               
           }else {
               if(!Character.isLetter(c)){
              // txtName.setEditable(false);
                lblCityError.setText("Enter a valid City");
               }
           }
    }//GEN-LAST:event_txtCityKeyPressed

    private void txtCommunityKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCommunityKeyPressed
        // TODO add your handling code here:
        
        char c =evt.getKeyChar();
           
           if(Character.isLetter(c) || Character.isWhitespace(c)|| Character.isISOControl(c)){
               lblCommunityError.setText(" ");
               txtCommunity.setEditable(true);
               
           }else {
               if(!Character.isLetter(c)){
              // txtName.setEditable(false);
                lblCommunityError.setText("Enter a valid Community");
               }
           }
    }//GEN-LAST:event_txtCommunityKeyPressed
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGoBack;
    private javax.swing.JButton btnUpdatePerson;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblAge1;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblCity1;
    private javax.swing.JLabel lblCityError;
    private javax.swing.JLabel lblCommunity;
    private javax.swing.JLabel lblCommunityError;
    private javax.swing.JLabel lblHouseAddress;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPersonAgeError;
    private javax.swing.JLabel lblPersonId;
    private javax.swing.JLabel lblPersonNameError;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblZipcodeError;
    private javax.swing.JRadioButton radioBtnFemale;
    private javax.swing.JRadioButton radioBtnMale;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtCommunity;
    private javax.swing.JTextField txtHouseAddress;
    private javax.swing.JTextField txtPersonId;
    private javax.swing.JTextField txtPersonName;
    private javax.swing.JTextField txtZipcode;
    // End of variables declaration//GEN-END:variables
}
